services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456-2458:2456-2458/udp
    environment:
      - SERVER_NAME="TitanCMD"
      - SERVER_WORLD=BISWORLD
      - SERVER_PASSWORD=poopy
      - SERVER_PUBLIC=1
      - TZ=Australia/Perth
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
      - ./valheim/backups:/home/steam/backups
    restart: unless-stopped
      